# Site settings
name: GG
email: 809537398@qq.com
author: GaoGang
url: https://809537398.github.io/
resume_site: https://809537398.github.io/
github: https://github.com/809537398
baseurl: ""
description: Actually, less is more!
meta_description: GG;个人博客;学而不思则罔;思而不学则殆;生命不止;折腾不休
motto: It's our wits that make us men.
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: 809537398
highlighter: Pygments

# Build settings
markdown: kramdown
kramdown:
  input: GFM

#FB:
#  comments :
    #provider : duoshuo
    #duoshuo:
    #    short_name : luoyan35714
    #disqus :
    #    short_name : freudkang
    # facebook :
    #   appid : 123
    #   num_posts: 5
    #   width: 580
    #   colorscheme: light